export const USER_PROFILE_LANDING_FORM_KEYS = {
  USER_DATA: 'userData',
  BK_USER_DATA:'backupUserData',
  USER_FIRST_NAME: 'userFirstName',
  USER_AGE: 'userAge',
  USER_COUNTRY: 'userCountry',
  SUBMIT_STATUS: 'submitStatus',
  VIEW_PROFILE_SUBMIT_STATUS:'viewProfileSubmitStatus',
  API_FAILURE: 'Api Failure',
  CURRENT_VIEW: 'currentView',
  YOUR_NAME: 'yourName',
  ALERT: 'alert',
  UPDATE_PROFILE_ALERT:'updateProfileAlert',
  UPDATE_IMAGES_ALERT:'updateImagesAlert',
  ABOUT_YOURSELF: 'about',
  YOUR_COMPANY: 'company',
  GENDER: 'gender',
  YOUR_SCHOOL: 'yourSchool',
  GRAB_A_BITE: 'grabABite',
  GET_A_DRINK: 'getADrink',
  HANGOUT_FOR_COFFEE: 'hangoutForCoffee',
  GO_OUT_FOR_MOVIE: 'goOutForMovie',
  GO_OUT_FOR_WALK: 'goOutForWalk',
  GYM_PARTNER: 'gymPartner',
  CONFIG_INTERESTS: 'configInterests',
  UPDATED_USER_DATA: 'updatedUserData',
  LOOKING_FOR_MEN: 'lookingForMen',
  LOOKING_FOR_WOMEN:'lookingForWomen',
  AGE_RANGE: 'ageRange',
  PREFERRED_AGE_MIN:'preferredAgeRangeMin',
  PREFERRED_AGE_MAX:'preferredAgeRangeMax',
  PAUSE_MY_CARD: 'isVisible',
  HIDE_MY_AGE: 'hideAge',
};

export const VIEWS = {
  VIEW_PROFILE: 'view-profile',
  EDIT_SETTINGS_VIEW: 'edit-settings-view',
  EDIT_PREFERENCES_VIEW: 'edit-preferences-view',
  UPDATE_IMAGES: 'update-images',
  LOGIN_VIEW:'login-view',
  PAIR_CENTERS_SCREEN:'pairCentersScreen',
};
